add_subdirectory(./A0MeshViewer)
set_target_properties (A0MeshViewer PROPERTIES FOLDER Assignments)

add_subdirectory(./A1SceneGraphViewer)
set_target_properties (A1SceneGraphViewer PROPERTIES FOLDER Assignments)

add_subdirectory(./V1BoltzmannFlow)
set_target_properties (V1BoltzmannFlow PROPERTIES FOLDER Assignments)

add_subdirectory(./V2BoltzmannKarmann)
set_target_properties (V2BoltzmannKarmann PROPERTIES FOLDER Assignments)

add_subdirectory(./V3MarchingCubes)
set_target_properties (V3MarchingCubes PROPERTIES FOLDER Assignments)